# Generated by Django 4.2.4 on 2023-08-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_experience_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default='Present', null=True),
        ),
    ]
