# Generated by Django 4.2.4 on 2023-08-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_alter_experience_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('skills', models.DateField(blank=True, null=True)),
                ('gpa', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
